current_dir=$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )
source ${current_dir}/prep_env.sh

export MATRIX_RUN_NOOP
unset MATRIX_RUN_INTERACTIVE
unset MATRIX_RUN_BLOCK
unset MATRIX_RUN_NO_INTERCHANGE
unset MATRIX_RUN_NO_TRANSPOSE
export MATRIX_RUN_PROG_FIRST=1
export MATRIX_RUN_REPORT=_papi
export MATRIX_RUN_REPEATS=5
export MATRIX_RUN_PAPI=PAPI_L1_DCM:PAPI_L2_DCM:PAPI_L3_TCM:PAPI_L2_DCA:PAPI_L3_DCA!PAPI_FP_INS:PAPI_FP_OPS:PAPI_TOT_INS
export MATRIX_RUN_INPUT=random_4096.csv