unset MATRIX_RUN_NOOP
unset MATRIX_RUN_INTERACTIVE
export MATRIX_RUN_BLOCK=16
unset MATRIX_RUN_NO_INTERCHANGE
unset MATRIX_RUN_NO_TRANSPOSE
# vector is 3
export MATRIX_RUN_PROG_FIRST=4
export MATRIX_RUN_REPORT=_omp
export MATRIX_RUN_REPEATS=8
# enable vector simd instructions
#export MATRIX_RUN_PAPI=PAPI_L1_DCM:PAPI_L2_DCM:PAPI_L3_TCM
unset MATRIX_RUN_PAPI
#export MATRIX_RUN_SIZES="32"
# use the two smaller datasets
export MATRIX_RUN_SIZES="2048"
#export MATRIX_RUN_SIZES="32 96 256"
#export MATRIX_RUN_SIZES="32 96 256 2048"
export MATRIX_RUN_THREADS_MAX=512
export MATRIX_RUN_THREADS_MIN=512
export MATRIX_RUN_THREADS_STEP=32

