unset MATRIX_RUN_NOOP
unset MATRIX_RUN_INTERACTIVE
export MATRIX_RUN_BLOCK=16
unset MATRIX_RUN_NO_INTERCHANGE
unset MATRIX_RUN_NO_TRANSPOSE
# vector is 3
export MATRIX_RUN_PROG_FIRST=3
export MATRIX_RUN_REPORT=_vector
export MATRIX_RUN_REPEATS=20
# enable vector simd instructions
export MATRIX_RUN_PAPI=PAPI_L1_DCM:PAPI_L2_DCM:PAPI_L3_TCM
#export MATRIX_RUN_SIZES="32"
# use the two smaller datasets
#export MATRIX_RUN_SIZES="32 96 256"
#export MATRIX_RUN_SIZES="32 96 256 2048"
